# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 08:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc_sh', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Short Description')),
                ('desc_lg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Long Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 4, 11, 8, 54, 16, 153384, tzinfo=utc), verbose_name='Created on:')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published on:')),
                ('read_time', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
