# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_lg',
            field=models.TextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_sh',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published on:'),
        ),
        migrations.AddField(
            model_name='tags',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
