# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 15:53
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170402_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 15, 53, 57, 185140, tzinfo=utc), verbose_name='Created on:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_lg',
            field=ckeditor.fields.RichTextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Post'),
        ),
    ]
