# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 20:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170402_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 20, 3, 47, 635784, tzinfo=utc), verbose_name='Created on:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_lg',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc_sh',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Short Description'),
        ),
    ]
