# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170411_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 6, 54, 7, 956165, tzinfo=utc), verbose_name='Created on:'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
