# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170411_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 6, 55, 31, 46350, tzinfo=utc), verbose_name='Created on:'),
        ),
    ]
